In [1]:
import numpy as np
from random import * 

In [2]:
a = np.array( [ [ randint(0,10) for x in range(3) ] for y in range(4) ] )

In [3]:
aa = np.eye(4 , dtype=int)  #dtype 預設 float
print( a , a/2 , aa , sep="\n" )    #+,-,*,/,==,!=,>=,<=

[[8 5 7]
 [5 9 4]
 [5 5 2]
 [1 2 7]]
[[4.  2.5 3.5]
 [2.5 4.5 2. ]
 [2.5 2.5 1. ]
 [0.5 1.  3.5]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [4]:
print( a>5 , np.all(a>5) , np.any(a>5) , sep="\n" )

[[ True False  True]
 [False  True False]
 [False False False]
 [False False  True]]
False
True


In [5]:
print( a.tolist() ) 
print( a )

[[8, 5, 7], [5, 9, 4], [5, 5, 2], [1, 2, 7]]
[[8 5 7]
 [5 9 4]
 [5 5 2]
 [1 2 7]]


In [6]:
print( a.shape )        # 幾X幾 的矩陣

(4, 3)


In [7]:
b = a.reshape( 12 )         # 改變維度
c = a.reshape( -1 )          # -1 : 自動計算
d = a.reshape( 2 , 2 , -1 )  # 2 X 2 X 3 矩陣

print( b , c , d , sep="\n" )

[8 5 7 5 9 4 5 5 2 1 2 7]
[8 5 7 5 9 4 5 5 2 1 2 7]
[[[8 5 7]
  [5 9 4]]

 [[5 5 2]
  [1 2 7]]]


In [8]:
tran_a = np.transpose(a)
print( tran_a )   #轉置矩陣

[[8 5 5 1]
 [5 9 5 2]
 [7 4 2 7]]


In [9]:
print( a.ndim )             #2維矩陣

2


In [10]:
a1 = np.array( [ [ 2 for i in range(4) ] for i in range(3) ] )
a2 = np.array( [ [ 3 for i in range(4) ] for i in range(3) ] )
print( np.multiply( a1 , a2 ) )
print( a1*a2 )

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]
[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [11]:
a3 = np.array( [ [ randint(1,10) for i in range(4) ] for i in range(4) ] )
a4 = np.linalg.inv(a3)
print( np.dot( a3 , a4 ) )

[[ 1.00000000e+00  0.00000000e+00  1.94289029e-16 -9.71445147e-17]
 [ 2.22044605e-16  1.00000000e+00  0.00000000e+00 -5.55111512e-17]
 [ 2.22044605e-16  0.00000000e+00  1.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  0.00000000e+00  1.11022302e-16  1.00000000e+00]]


In [12]:
print( np.dot( a , tran_a ) )   #內積

[[138 113  79  67]
 [113 122  78  51]
 [ 79  78  54  29]
 [ 67  51  29  54]]


In [13]:
print( np.outer( a , tran_a ) )   #外積

[[64 40 40  8 40 72 40 16 56 32 16 56]
 [40 25 25  5 25 45 25 10 35 20 10 35]
 [56 35 35  7 35 63 35 14 49 28 14 49]
 [40 25 25  5 25 45 25 10 35 20 10 35]
 [72 45 45  9 45 81 45 18 63 36 18 63]
 [32 20 20  4 20 36 20  8 28 16  8 28]
 [40 25 25  5 25 45 25 10 35 20 10 35]
 [40 25 25  5 25 45 25 10 35 20 10 35]
 [16 10 10  2 10 18 10  4 14  8  4 14]
 [ 8  5  5  1  5  9  5  2  7  4  2  7]
 [16 10 10  2 10 18 10  4 14  8  4 14]
 [56 35 35  7 35 63 35 14 49 28 14 49]]
